### ISSUE TITLE
language detection

### ISSUE THREAD

**Issue by ranjithshegde** [davidgranstrom/sclang-lsp-stdio#1]
As sc-lsp is in the works, and probably the goal is to add this to `nvim-lspconfig`, perhaps its time to add SuperCollider to upstream ftdetect. Requiring a plugin to ftdetect an LSP lang can break `lspconfig` calling lua modules for many users.

I propose a PR to vim (not Neovim) to add SuperCollider ftdetect, which can be merged as a vim-patch in neovim. (There is precedent, my PR for orgmode detection in vim was merged). I would have created a simple PR, except `*.sc` is shared between SuperCollider and Scala. Needs regex to differentiate between filetypes.

@davidgranstrom Can you or any one of the wonderful scnvim contributors have enough knowledge about regexes to get this started?

**Comment by davidgranstrom** [comment]
@ranjithshegde Thanks for bringing this up, I'm not sure though how the file type detection would be a problem for `nvim-lspconfig` would you mind elaborating this concern?

**Comment by ranjithshegde** [comment]
@davidgranstrom thanks for your note. The issue was on my end, about how I was calling an filetype autocmd with a `once` flag that would clear the autocmd after loading the modules. But just changing the sequence of when its being called fixes that.

I am working on a PR for vim
```vim
au BufNewFile,BufRead *.sc	
    \ if getline(1).getline(2).getline(3).getline(4).getline(5).getline(6).getline(7).getline(8).getline(9) =~# '[A-Za-z0-9]*\s:\s[A-Za-z0-9]\|var\s<\|classvar\s<\|\^this\.\||\w*|' |
	\   setf supercollider |
    \ else |
	\   setf scala |
	\ endif

" scdoc
au BufNewFile,BufRead *.scd			
    \ if getline(1) =~# '\%^\S\+(\d[0-9A-Za-z]*)\%(\s\+\"[^"]*\"\%(\s\+\"[^"]*\"\)\=\)\=$' |
      \ setf scdoc |
    \ else |
    \  setf supercollider |
    \ endif


au BufNewFile,BufRead *.quark		setf supercollider

```
I will improve this sometime tomorrow. Any other patterns you recommend?  Here scdoc does not refer to "our" scdoc but upstream vim has another man page generator filetype called scdoc. But, *.scd and *.sc will be recognized as supercollider (or scala based on regex)

**Comment by ranjithshegde** [comment]
based on matrix discussion with the devs, and as per Bram's advice I have done it like this in `dist/ft.vim`
```vim
# This function checks first 25 lines of file extension "sc" to resolve
# detection between scala and SuperCollider
export def SClang()
  for lnum in range(1, min([line("$"), 25]))
    var line = getline(lnum)
    if line =~# '[A-Za-z0-9]*\s:\s[A-Za-z0-9]\|var\s<\|classvar\s<\|\^this\.\||\w*|'
      setf supercollider
      return
    else
      setf scala
    endif
  endfor
enddef
```
And this in `filetype.vim`
```vim
au BufNewFile,BufRead *.sc		call dist#ft#SClang()
au BufNewFile,BufRead *.quark      setf supercollider

au BufNewFile,BufRead *.scd			
    \ if getline(1) =~# '\%^\S\+(\d[0-9A-Za-z]*)\%(\s\+\"[^"]*\"\%(\s\+\"[^"]*\"\)\=\)\=$' |
    \   setf scdoc |
    \ else |
    \   setf supercollider |
    \ endif
```
